# Generated by Django 5.2.17 on 2026-09-11 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('is_cash', models.BooleanField(default=False)),
                ('is_group', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_through', models.DateField(blank=True, null=True)),
                ('require_evidence', models.BooleanField(default=False)),
                ('approver_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('closed', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='financial_year_date_order')],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(unique=True)),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('payment', 'Payment'), ('receipt', 'Receipt'), ('transfer', 'Transfer'), ('journal', 'Journal')], max_length=12)),
                ('narration', models.CharField(max_length=1000)),
                ('party_name', models.CharField(blank=True, max_length=180)),
                ('handled_by', models.CharField(blank=True, max_length=120)),
                ('method', models.CharField(blank=True, max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='draft', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('posted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField(blank=True, max_length=1000)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approver_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.role')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='core.voucher')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mime', models.CharField(max_length=40)),
                ('content', models.BinaryField()),
                ('digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='core.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.project')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.voucher')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='one_positive_journal_side')],
            },
        ),
    ]
