# Generated by Django 5.2.17 on 2026-09-11 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_account_financesettings_financialyear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('window', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=8)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(unique=True)),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment')], max_length=8)),
                ('party', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('handled_by', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=1000)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approver_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.role')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.registercategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.registersource')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_register_amount')],
            },
        ),
    ]
