# Generated by Django 5.2.17 on 2026-09-12 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recoverylimit_registercategory_registersource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('mime', models.CharField(max_length=40)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('content', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(null=True)),
                ('withdrawal_reason', models.CharField(blank=True, max_length=500)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.registerentry')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
