# Generated by Django 5.2.17 on 2026-09-13 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registerattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=180)),
                ('file_hash', models.CharField(max_length=64)),
                ('sheet', models.CharField(max_length=100)),
                ('header_row', models.PositiveIntegerField()),
                ('headers', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('configuration', models.JSONField(default=dict)),
                ('preview', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='staged', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterImportOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64)),
                ('sheet', models.CharField(max_length=100)),
                ('source_row', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origins', to='core.registerimport')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='import_origin', to='core.registerentry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('file_hash', 'sheet', 'source_row'), name='unique_register_source_row')],
            },
        ),
    ]
