# Generated by Django 5.2.17 on 2026-09-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_registerreporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='party',
            name='entity_type',
            field=models.CharField(choices=[('organization', 'Organization'), ('person', 'Person')], default='organization', max_length=12),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.party'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='registercategory',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='registercategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.registercategory'),
        ),
        migrations.AddField(
            model_name='registerentry',
            name='beneficiary',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='registerentry',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register_entries', to='core.party'),
        ),
        migrations.AddField(
            model_name='registerentry',
            name='nature',
            field=models.CharField(choices=[('unclassified', 'Pending classification'), ('operating', 'Operating receipt / payment'), ('advance', 'Advance'), ('loan', 'Loan principal'), ('deposit', 'Security / refundable deposit'), ('investment', 'Investment principal'), ('capital', 'Capital contribution / distribution'), ('donation', 'Donation')], default='unclassified', max_length=24),
        ),
        migrations.AddField(
            model_name='registersource',
            name='account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='registersource',
            name='account_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='registersource',
            name='bank',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registersource',
            name='branch',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='registersource',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AlterField(
            model_name='party',
            name='kind',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('both', 'Both'), ('contractor', 'Contractor'), ('employee', 'Employee'), ('other', 'Other')], max_length=12),
        ),
    ]
