# Generated by Django 5.2.17 on 2026-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_registerallocation_registerposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerentry',
            name='reporting_class',
            field=models.CharField(choices=[('unclassified', 'Pending classification'), ('income', 'Income received'), ('expense', 'Expense paid'), ('other', 'Other funds movement')], default='unclassified', db_default='unclassified', max_length=16),
        ),
    ]
