# Generated by Django 5.2.17 on 2026-09-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_register_income_expense_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerattachment',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.registerposition'),
        ),
        migrations.AlterField(
            model_name='registerattachment',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.registerentry'),
        ),
        migrations.AddConstraint(
            model_name='registerattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry__isnull', False), ('position__isnull', True)), models.Q(('entry__isnull', True), ('position__isnull', False)), _connector='OR'), name='register_attachment_single_record'),
        ),
    ]
